-- Actualización: sitio web cliente y plantillas de avisos
-- Fecha: 2026-03-23
-- ----------------------------------------------

ALTER TABLE `clientes`
  ADD COLUMN IF NOT EXISTS `sitio_web` VARCHAR(180) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `email_templates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `template_key` VARCHAR(80) NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `body_html` MEDIUMTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_templates_key_unique` (`template_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `email_templates` (`template_key`, `subject`, `body_html`)
VALUES
  ('aviso_1', 'Aviso 1: {{servicio_nombre}} - {{cliente_nombre}}', '<p style=\"font-family:Arial,sans-serif;\">Estimado/a {{cliente_nombre}},</p><p style=\"font-family:Arial,sans-serif;\">Junto con saludar, le informamos que su <strong>servicio digital contratado</strong> se encuentra próximo a su fecha de vencimiento.</p><p style=\"font-family:Arial,sans-serif;\"><strong>Servicio:</strong> {{servicio_nombre}}<br><strong>Monto:</strong> {{monto}}<br><strong>Fecha de aviso:</strong> {{fecha_aviso}}<br><strong>Referencia:</strong> {{referencia}}</p><p style=\"font-family:Arial,sans-serif;\">Es importante considerar que la <strong>no renovación oportuna</strong> de este servicio puede afectar directamente la <strong>disponibilidad de su sitio web, correos corporativos y presencia en internet</strong>, lo que a su vez impacta la <strong>imagen, posicionamiento y continuidad operativa de su empresa frente a clientes y proveedores</strong>.</p><p style=\"font-family:Arial,sans-serif;\">Para evitar interrupciones y asegurar la correcta continuidad de sus servicios digitales, le recomendamos realizar el pago dentro del plazo indicado.</p><p style=\"font-family:Arial,sans-serif;\">Ante cualquier consulta, aclaración o si requiere apoyo con el proceso de renovación, puede responder directamente a este correo y con gusto lo asistiremos.</p><p style=\"font-family:Arial,sans-serif;\">Agradecemos su atención y preferencia.</p><p style=\"font-family:Arial,sans-serif;\">Atentamente,<br><strong>Departamento de Soporte y Servicios Digitales</strong><br>{{municipalidad_nombre}}</p>'),
  ('aviso_2', 'Aviso 2: {{servicio_nombre}} - {{cliente_nombre}}', '<p style=\"font-family:Arial,sans-serif;\">Estimado/a {{cliente_nombre}},</p><p style=\"font-family:Arial,sans-serif;\">Junto con saludar, le informamos que su <strong>servicio digital contratado</strong> se encuentra próximo a su fecha de vencimiento.</p><p style=\"font-family:Arial,sans-serif;\"><strong>Servicio:</strong> {{servicio_nombre}}<br><strong>Monto:</strong> {{monto}}<br><strong>Fecha de aviso:</strong> {{fecha_aviso}}<br><strong>Referencia:</strong> {{referencia}}</p><p style=\"font-family:Arial,sans-serif;\">Es importante considerar que la <strong>no renovación oportuna</strong> de este servicio puede afectar directamente la <strong>disponibilidad de su sitio web, correos corporativos y presencia en internet</strong>, lo que a su vez impacta la <strong>imagen, posicionamiento y continuidad operativa de su empresa frente a clientes y proveedores</strong>.</p><p style=\"font-family:Arial,sans-serif;\">Para evitar interrupciones y asegurar la correcta continuidad de sus servicios digitales, le recomendamos realizar el pago dentro del plazo indicado.</p><p style=\"font-family:Arial,sans-serif;\">Ante cualquier consulta, aclaración o si requiere apoyo con el proceso de renovación, puede responder directamente a este correo y con gusto lo asistiremos.</p><p style=\"font-family:Arial,sans-serif;\">Agradecemos su atención y preferencia.</p><p style=\"font-family:Arial,sans-serif;\">Atentamente,<br><strong>Departamento de Soporte y Servicios Digitales</strong><br>{{municipalidad_nombre}}</p>'),
  ('aviso_3', 'Aviso 3: {{servicio_nombre}} - {{cliente_nombre}}', '<p style=\"font-family:Arial,sans-serif;\">Estimado/a {{cliente_nombre}},</p><p style=\"font-family:Arial,sans-serif;\">Junto con saludar, le informamos que su <strong>servicio digital contratado</strong> se encuentra próximo a su fecha de vencimiento.</p><p style=\"font-family:Arial,sans-serif;\"><strong>Servicio:</strong> {{servicio_nombre}}<br><strong>Monto:</strong> {{monto}}<br><strong>Fecha de aviso:</strong> {{fecha_aviso}}<br><strong>Referencia:</strong> {{referencia}}</p><p style=\"font-family:Arial,sans-serif;\">Es importante considerar que la <strong>no renovación oportuna</strong> de este servicio puede afectar directamente la <strong>disponibilidad de su sitio web, correos corporativos y presencia en internet</strong>, lo que a su vez impacta la <strong>imagen, posicionamiento y continuidad operativa de su empresa frente a clientes y proveedores</strong>.</p><p style=\"font-family:Arial,sans-serif;\">Para evitar interrupciones y asegurar la correcta continuidad de sus servicios digitales, le recomendamos realizar el pago dentro del plazo indicado.</p><p style=\"font-family:Arial,sans-serif;\">Ante cualquier consulta, aclaración o si requiere apoyo con el proceso de renovación, puede responder directamente a este correo y con gusto lo asistiremos.</p><p style=\"font-family:Arial,sans-serif;\">Agradecemos su atención y preferencia.</p><p style=\"font-family:Arial,sans-serif;\">Atentamente,<br><strong>Departamento de Soporte y Servicios Digitales</strong><br>{{municipalidad_nombre}}</p>')
ON DUPLICATE KEY UPDATE
  subject = VALUES(subject),
  body_html = VALUES(body_html);
